server:
  port: 8050
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO
zuul:
  ignoredServices: '*'
  routes:
    app-cusume-hystrix:
      path: /user/**
      serviceId: consumer-hystrix
    app-sidecar:
      path: /sidecar/**
      serviceId: sidecar